In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [1]:
minhaLista = ['Vitória Amorim', 18, 51.5, 1.68]

print('minha idade é', minhaLista[1])

print('minha altura é de ', minhaLista[3])

print('meu nome é ', minhaLista[1])

print('meu peso é ', minhaLista[2])

minha idade é 18
minha altura é de  1.68
meu nome é  18
meu peso é  51.5


In [2]:
for i in minhaLista:
  print(i)

Vitória Amorim
18
51.5
1.68


In [16]:
lista = ["celular","tablet", "computador","relogio", "assistente"]
print(lista[1:4])

['tablet', 'computador', 'relogio']


In [17]:
print(lista[:2])
print(lista[2:])

['celular', 'tablet']
['computador', 'relogio', 'assistente']


In [18]:
lista.append("televisão")
print(lista)

#remove pelo conteudo
lista.remove("televisão")
print(lista)

#remove pelo índice
lista.pop(0)
print(lista)

['celular', 'tablet', 'computador', 'relogio', 'assistente', 'televisão']
['celular', 'tablet', 'computador', 'relogio', 'assistente']
['tablet', 'computador', 'relogio', 'assistente']


In [19]:
print(lista)
lista = lista[2:]
print(lista)

['tablet', 'computador', 'relogio', 'assistente']
['relogio', 'assistente']


In [5]:
import numpy as np
arr = np.array(50)
print(arr)

array = np.array([1, 2, 3, 4, 5])
print(array)

array_grande = np.array([[1,2,3,4,5],[5,4,3,2,2,1]])
print(array_grande)

50
[1 2 3 4 5]
[list([1, 2, 3, 4, 5]) list([5, 4, 3, 2, 2, 1])]


<ipython-input-5-b1bc3ffbe3a8>:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_grande = np.array([[1,2,3,4,5],[5,4,3,2,2,1]])


In [6]:
array2 = np.array([10,20,33,40])
print(array2[2] + array2[3])

73


In [7]:
array3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('O segundo elemento da primeira linha é:', array3[0, 1])

O segundo elemento da primeira linha é: 2


In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print("o segundo elemento da segunda linha é:", arr[1, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
o segundo elemento da segunda linha é: 7


In [21]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2.shape)

(2, 5)
